package com.yinlian.wssc.web.po;

import java.util.ArrayList;
import java.util.List;

import com.yinlian.wssc.web.dto.NavclassfyDto;

public class SnewsClassExample extends SnewsClass{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public SnewsClassExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}
    
    protected List<SnewsClassExample>list;

    public List<SnewsClassExample> getList() {
		return list;
	}

	public void setList(List<SnewsClassExample> list) {
		this.list = list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("sort is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("sort is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("sort =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("sort <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("sort >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("sort <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("sort <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("sort in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("sort not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("sort between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("sort not between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andPidIsNull() {
			addCriterion("pid is null");
			return (Criteria) this;
		}

		public Criteria andPidIsNotNull() {
			addCriterion("pid is not null");
			return (Criteria) this;
		}

		public Criteria andPidEqualTo(Integer value) {
			addCriterion("pid =", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotEqualTo(Integer value) {
			addCriterion("pid <>", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThan(Integer value) {
			addCriterion("pid >", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThanOrEqualTo(Integer value) {
			addCriterion("pid >=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThan(Integer value) {
			addCriterion("pid <", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThanOrEqualTo(Integer value) {
			addCriterion("pid <=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidIn(List<Integer> values) {
			addCriterion("pid in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotIn(List<Integer> values) {
			addCriterion("pid not in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidBetween(Integer value1, Integer value2) {
			addCriterion("pid between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotBetween(Integer value1, Integer value2) {
			addCriterion("pid not between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andEx1IsNull() {
			addCriterion("ex1 is null");
			return (Criteria) this;
		}

		public Criteria andEx1IsNotNull() {
			addCriterion("ex1 is not null");
			return (Criteria) this;
		}

		public Criteria andEx1EqualTo(String value) {
			addCriterion("ex1 =", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotEqualTo(String value) {
			addCriterion("ex1 <>", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1GreaterThan(String value) {
			addCriterion("ex1 >", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1GreaterThanOrEqualTo(String value) {
			addCriterion("ex1 >=", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1LessThan(String value) {
			addCriterion("ex1 <", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1LessThanOrEqualTo(String value) {
			addCriterion("ex1 <=", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1Like(String value) {
			addCriterion("ex1 like", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotLike(String value) {
			addCriterion("ex1 not like", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1In(List<String> values) {
			addCriterion("ex1 in", values, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotIn(List<String> values) {
			addCriterion("ex1 not in", values, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1Between(String value1, String value2) {
			addCriterion("ex1 between", value1, value2, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotBetween(String value1, String value2) {
			addCriterion("ex1 not between", value1, value2, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx2IsNull() {
			addCriterion("ex2 is null");
			return (Criteria) this;
		}

		public Criteria andEx2IsNotNull() {
			addCriterion("ex2 is not null");
			return (Criteria) this;
		}

		public Criteria andEx2EqualTo(String value) {
			addCriterion("ex2 =", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotEqualTo(String value) {
			addCriterion("ex2 <>", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2GreaterThan(String value) {
			addCriterion("ex2 >", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2GreaterThanOrEqualTo(String value) {
			addCriterion("ex2 >=", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2LessThan(String value) {
			addCriterion("ex2 <", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2LessThanOrEqualTo(String value) {
			addCriterion("ex2 <=", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2Like(String value) {
			addCriterion("ex2 like", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotLike(String value) {
			addCriterion("ex2 not like", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2In(List<String> values) {
			addCriterion("ex2 in", values, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotIn(List<String> values) {
			addCriterion("ex2 not in", values, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2Between(String value1, String value2) {
			addCriterion("ex2 between", value1, value2, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotBetween(String value1, String value2) {
			addCriterion("ex2 not between", value1, value2, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx3IsNull() {
			addCriterion("ex3 is null");
			return (Criteria) this;
		}

		public Criteria andEx3IsNotNull() {
			addCriterion("ex3 is not null");
			return (Criteria) this;
		}

		public Criteria andEx3EqualTo(String value) {
			addCriterion("ex3 =", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotEqualTo(String value) {
			addCriterion("ex3 <>", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3GreaterThan(String value) {
			addCriterion("ex3 >", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3GreaterThanOrEqualTo(String value) {
			addCriterion("ex3 >=", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3LessThan(String value) {
			addCriterion("ex3 <", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3LessThanOrEqualTo(String value) {
			addCriterion("ex3 <=", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3Like(String value) {
			addCriterion("ex3 like", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotLike(String value) {
			addCriterion("ex3 not like", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3In(List<String> values) {
			addCriterion("ex3 in", values, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotIn(List<String> values) {
			addCriterion("ex3 not in", values, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3Between(String value1, String value2) {
			addCriterion("ex3 between", value1, value2, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotBetween(String value1, String value2) {
			addCriterion("ex3 not between", value1, value2, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx4IsNull() {
			addCriterion("ex4 is null");
			return (Criteria) this;
		}

		public Criteria andEx4IsNotNull() {
			addCriterion("ex4 is not null");
			return (Criteria) this;
		}

		public Criteria andEx4EqualTo(Integer value) {
			addCriterion("ex4 =", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotEqualTo(Integer value) {
			addCriterion("ex4 <>", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4GreaterThan(Integer value) {
			addCriterion("ex4 >", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4GreaterThanOrEqualTo(Integer value) {
			addCriterion("ex4 >=", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4LessThan(Integer value) {
			addCriterion("ex4 <", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4LessThanOrEqualTo(Integer value) {
			addCriterion("ex4 <=", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4In(List<Integer> values) {
			addCriterion("ex4 in", values, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotIn(List<Integer> values) {
			addCriterion("ex4 not in", values, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4Between(Integer value1, Integer value2) {
			addCriterion("ex4 between", value1, value2, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotBetween(Integer value1, Integer value2) {
			addCriterion("ex4 not between", value1, value2, "ex4");
			return (Criteria) this;
		}

		public Criteria andCtypeIsNull() {
			addCriterion("ctype is null");
			return (Criteria) this;
		}

		public Criteria andCtypeIsNotNull() {
			addCriterion("ctype is not null");
			return (Criteria) this;
		}

		public Criteria andCtypeEqualTo(Integer value) {
			addCriterion("ctype =", value, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeNotEqualTo(Integer value) {
			addCriterion("ctype <>", value, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeGreaterThan(Integer value) {
			addCriterion("ctype >", value, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ctype >=", value, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeLessThan(Integer value) {
			addCriterion("ctype <", value, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeLessThanOrEqualTo(Integer value) {
			addCriterion("ctype <=", value, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeIn(List<Integer> values) {
			addCriterion("ctype in", values, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeNotIn(List<Integer> values) {
			addCriterion("ctype not in", values, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeBetween(Integer value1, Integer value2) {
			addCriterion("ctype between", value1, value2, "ctype");
			return (Criteria) this;
		}

		public Criteria andCtypeNotBetween(Integer value1, Integer value2) {
			addCriterion("ctype not between", value1, value2, "ctype");
			return (Criteria) this;
		}

		public Criteria andFpathIsNull() {
			addCriterion("fpath is null");
			return (Criteria) this;
		}

		public Criteria andFpathIsNotNull() {
			addCriterion("fpath is not null");
			return (Criteria) this;
		}

		public Criteria andFpathEqualTo(String value) {
			addCriterion("fpath =", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathNotEqualTo(String value) {
			addCriterion("fpath <>", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathGreaterThan(String value) {
			addCriterion("fpath >", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathGreaterThanOrEqualTo(String value) {
			addCriterion("fpath >=", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathLessThan(String value) {
			addCriterion("fpath <", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathLessThanOrEqualTo(String value) {
			addCriterion("fpath <=", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathLike(String value) {
			addCriterion("fpath like", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathNotLike(String value) {
			addCriterion("fpath not like", value, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathIn(List<String> values) {
			addCriterion("fpath in", values, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathNotIn(List<String> values) {
			addCriterion("fpath not in", values, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathBetween(String value1, String value2) {
			addCriterion("fpath between", value1, value2, "fpath");
			return (Criteria) this;
		}

		public Criteria andFpathNotBetween(String value1, String value2) {
			addCriterion("fpath not between", value1, value2, "fpath");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(Integer value) {
			addCriterion("level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(Integer value) {
			addCriterion("level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(Integer value) {
			addCriterion("level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(Integer value) {
			addCriterion("level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(Integer value) {
			addCriterion("level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<Integer> values) {
			addCriterion("level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<Integer> values) {
			addCriterion("level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(Integer value1, Integer value2) {
			addCriterion("level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("level not between", value1, value2, "level");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table s_news_class
	 * @mbggenerated  Wed Sep 07 10:54:49 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_news_class
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 06 10:45:18 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}