package com.yinlian.wssc.web.po;

import java.util.Date;

public class Groupbuyinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.id
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.title
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.starttime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.endtime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.price
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.num
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.createtime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.imgurl
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.mbgrade
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer mbgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.state
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.ynum
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer ynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.pnum
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer pnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.stitle
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private String stitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.code
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.cid
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.sid
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.sort
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.auditing
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer auditing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.yprice
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Double yprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.isower
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private Integer isower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupbuyinfo.depict
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    private String depict;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.id
     *
     * @return the value of groupbuyinfo.id
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.id
     *
     * @param id the value for groupbuyinfo.id
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.title
     *
     * @return the value of groupbuyinfo.title
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.title
     *
     * @param title the value for groupbuyinfo.title
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.starttime
     *
     * @return the value of groupbuyinfo.starttime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.starttime
     *
     * @param starttime the value for groupbuyinfo.starttime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.endtime
     *
     * @return the value of groupbuyinfo.endtime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.endtime
     *
     * @param endtime the value for groupbuyinfo.endtime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.price
     *
     * @return the value of groupbuyinfo.price
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.price
     *
     * @param price the value for groupbuyinfo.price
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.num
     *
     * @return the value of groupbuyinfo.num
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.num
     *
     * @param num the value for groupbuyinfo.num
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.createtime
     *
     * @return the value of groupbuyinfo.createtime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.createtime
     *
     * @param createtime the value for groupbuyinfo.createtime
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.imgurl
     *
     * @return the value of groupbuyinfo.imgurl
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.imgurl
     *
     * @param imgurl the value for groupbuyinfo.imgurl
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.mbgrade
     *
     * @return the value of groupbuyinfo.mbgrade
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getMbgrade() {
        return mbgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.mbgrade
     *
     * @param mbgrade the value for groupbuyinfo.mbgrade
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setMbgrade(Integer mbgrade) {
        this.mbgrade = mbgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.state
     *
     * @return the value of groupbuyinfo.state
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.state
     *
     * @param state the value for groupbuyinfo.state
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.ynum
     *
     * @return the value of groupbuyinfo.ynum
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getYnum() {
        return ynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.ynum
     *
     * @param ynum the value for groupbuyinfo.ynum
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setYnum(Integer ynum) {
        this.ynum = ynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.pnum
     *
     * @return the value of groupbuyinfo.pnum
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getPnum() {
        return pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.pnum
     *
     * @param pnum the value for groupbuyinfo.pnum
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setPnum(Integer pnum) {
        this.pnum = pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.stitle
     *
     * @return the value of groupbuyinfo.stitle
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public String getStitle() {
        return stitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.stitle
     *
     * @param stitle the value for groupbuyinfo.stitle
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setStitle(String stitle) {
        this.stitle = stitle == null ? null : stitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.code
     *
     * @return the value of groupbuyinfo.code
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.code
     *
     * @param code the value for groupbuyinfo.code
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.cid
     *
     * @return the value of groupbuyinfo.cid
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.cid
     *
     * @param cid the value for groupbuyinfo.cid
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.sid
     *
     * @return the value of groupbuyinfo.sid
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.sid
     *
     * @param sid the value for groupbuyinfo.sid
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.sort
     *
     * @return the value of groupbuyinfo.sort
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.sort
     *
     * @param sort the value for groupbuyinfo.sort
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.auditing
     *
     * @return the value of groupbuyinfo.auditing
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getAuditing() {
        return auditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.auditing
     *
     * @param auditing the value for groupbuyinfo.auditing
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setAuditing(Integer auditing) {
        this.auditing = auditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.yprice
     *
     * @return the value of groupbuyinfo.yprice
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Double getYprice() {
        return yprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.yprice
     *
     * @param yprice the value for groupbuyinfo.yprice
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setYprice(Double yprice) {
        this.yprice = yprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.isower
     *
     * @return the value of groupbuyinfo.isower
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public Integer getIsower() {
        return isower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.isower
     *
     * @param isower the value for groupbuyinfo.isower
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setIsower(Integer isower) {
        this.isower = isower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupbuyinfo.depict
     *
     * @return the value of groupbuyinfo.depict
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public String getDepict() {
        return depict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupbuyinfo.depict
     *
     * @param depict the value for groupbuyinfo.depict
     *
     * @mbggenerated Mon Sep 12 11:27:53 CST 2016
     */
    public void setDepict(String depict) {
        this.depict = depict == null ? null : depict.trim();
    }
}