package com.yinlian.wssc.web.po;

import java.util.Date;

public class VGroupSku {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.id
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.sid
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.title
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.endtime
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.starttime
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Date starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.num
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.pnum
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Integer pnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.price
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.state
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.ynum
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Integer ynum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.kname
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private String kname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.kprice
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private Float kprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.sname
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private String sname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.cname
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_group_sku.depict
	 * 
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	private String depict;
	private Integer cid;
	private String imgurl;

	public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.id
	 * 
	 * @return the value of v_group_sku.id
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.id
	 * 
	 * @param id
	 *            the value for v_group_sku.id
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.sid
	 * 
	 * @return the value of v_group_sku.sid
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.sid
	 * 
	 * @param sid
	 *            the value for v_group_sku.sid
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.title
	 * 
	 * @return the value of v_group_sku.title
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.title
	 * 
	 * @param title
	 *            the value for v_group_sku.title
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.endtime
	 * 
	 * @return the value of v_group_sku.endtime
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.endtime
	 * 
	 * @param endtime
	 *            the value for v_group_sku.endtime
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.starttime
	 * 
	 * @return the value of v_group_sku.starttime
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.starttime
	 * 
	 * @param starttime
	 *            the value for v_group_sku.starttime
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.num
	 * 
	 * @return the value of v_group_sku.num
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.num
	 * 
	 * @param num
	 *            the value for v_group_sku.num
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.pnum
	 * 
	 * @return the value of v_group_sku.pnum
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Integer getPnum() {
		return pnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.pnum
	 * 
	 * @param pnum
	 *            the value for v_group_sku.pnum
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setPnum(Integer pnum) {
		this.pnum = pnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.price
	 * 
	 * @return the value of v_group_sku.price
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.price
	 * 
	 * @param price
	 *            the value for v_group_sku.price
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.state
	 * 
	 * @return the value of v_group_sku.state
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.state
	 * 
	 * @param state
	 *            the value for v_group_sku.state
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.ynum
	 * 
	 * @return the value of v_group_sku.ynum
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Integer getYnum() {
		return ynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.ynum
	 * 
	 * @param ynum
	 *            the value for v_group_sku.ynum
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setYnum(Integer ynum) {
		this.ynum = ynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.kname
	 * 
	 * @return the value of v_group_sku.kname
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public String getKname() {
		return kname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.kname
	 * 
	 * @param kname
	 *            the value for v_group_sku.kname
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setKname(String kname) {
		this.kname = kname == null ? null : kname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.kprice
	 * 
	 * @return the value of v_group_sku.kprice
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public Float getKprice() {
		return kprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.kprice
	 * 
	 * @param kprice
	 *            the value for v_group_sku.kprice
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setKprice(Float kprice) {
		this.kprice = kprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.sname
	 * 
	 * @return the value of v_group_sku.sname
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.sname
	 * 
	 * @param sname
	 *            the value for v_group_sku.sname
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setSname(String sname) {
		this.sname = sname == null ? null : sname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.cname
	 * 
	 * @return the value of v_group_sku.cname
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.cname
	 * 
	 * @param cname
	 *            the value for v_group_sku.cname
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setCname(String cname) {
		this.cname = cname == null ? null : cname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_group_sku.depict
	 * 
	 * @return the value of v_group_sku.depict
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public String getDepict() {
		return depict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_group_sku.depict
	 * 
	 * @param depict
	 *            the value for v_group_sku.depict
	 * @mbggenerated Mon Sep 05 14:19:12 CST 2016
	 */
	public void setDepict(String depict) {
		this.depict = depict == null ? null : depict.trim();
	}

}