package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.web.po.GroupbuyClass;
import com.yinlian.wssc.web.po.GroupbuyClassExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupbuyClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int countByExample(GroupbuyClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int deleteByExample(GroupbuyClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int insert(GroupbuyClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int insertSelective(GroupbuyClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    List<GroupbuyClass> selectByExample(GroupbuyClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    GroupbuyClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupbuyClass record, @Param("example") GroupbuyClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int updateByExample(@Param("record") GroupbuyClass record, @Param("example") GroupbuyClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int updateByPrimaryKeySelective(GroupbuyClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupbuyclass
     *
     * @mbggenerated Mon Aug 29 17:34:49 CST 2016
     */
    int updateByPrimaryKey(GroupbuyClass record);
    
    List<GroupbuyClass> selectByCriteriaPage(PageBeanUtil pageBeanUtil)throws Exception;
    
    int delById(Integer id)throws Exception;
    
    GroupbuyClass selectById(Integer id)throws Exception;
    
    int updateById(GroupbuyClass gbc)throws Exception;

	List<GroupbuyClass> getAllList() throws Exception;
    
}