package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.web.dto.SearchkeyDto;
import com.yinlian.wssc.web.po.AdvertImg;
import com.yinlian.wssc.web.po.Searchkey;
import com.yinlian.wssc.web.po.SearchkeyExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SearchkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int countByExample(SearchkeyExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int deleteByExample(SearchkeyExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int insert(Searchkey record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int insertSelective(Searchkey record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    List<Searchkey> selectByExample(SearchkeyExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    Searchkey selectByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") Searchkey record, @Param("example") SearchkeyExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int updateByExample(@Param("record") Searchkey record, @Param("example") SearchkeyExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int updateByPrimaryKeySelective(Searchkey record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchkey
     *
     * @mbggenerated Wed Jun 22 17:27:23 CST 2016
     */
    int updateByPrimaryKey(Searchkey record)throws Exception;


	List<SearchkeyDto> getListByPage(PageBeanUtil pBeanUtil)throws Exception;

	int orderByUpd(SearchkeyDto dto)throws Exception;

	List<Searchkey> getSearchkeys(int usesites)throws Exception;
}