package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.web.po.Payconfig;
import com.yinlian.wssc.web.po.PayconfigExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PayconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int countByExample(PayconfigExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int deleteByExample(PayconfigExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int insert(Payconfig record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int insertSelective(Payconfig record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    List<Payconfig> selectByExample(PayconfigExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    Payconfig selectByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") Payconfig record, @Param("example") PayconfigExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int updateByExample(@Param("record") Payconfig record, @Param("example") PayconfigExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int updateByPrimaryKeySelective(Payconfig record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int updateByPrimaryKey(Payconfig record)throws Exception;
    
    Payconfig getByType(Integer paytype,Integer sites)throws Exception;
    
    List<Payconfig> getListByPage(PageBeanUtil pBeanUtil)throws Exception;
}