package com.yinlian.wssc.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yinlian.wssc.web.po.Hotcity;
import com.yinlian.wssc.web.po.HotcityExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

public interface HotcityMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int countByExample(HotcityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int deleteByExample(HotcityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int insert(Hotcity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int insertSelective(Hotcity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	List<Hotcity> selectByExample(HotcityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	Hotcity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Hotcity record, @Param("example") HotcityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int updateByExample(@Param("record") Hotcity record, @Param("example") HotcityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int updateByPrimaryKeySelective(Hotcity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotcity
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	int updateByPrimaryKey(Hotcity record);

	List<Hotcity> queryHotCityPage(PageBeanUtil pageBeanUtil) throws Exception;

	List<Hotcity> getAllList() throws Exception;

	Hotcity selCity(String code) throws Exception;

}