package com.yinlian.wssc.web.po;

public class IntegraproductWithBLOBs extends Integraproduct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column integraproduct.content
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column integraproduct.packing
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	private String packing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column integraproduct.afterservice
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	private String afterservice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column integraproduct.content
	 * @return  the value of integraproduct.content
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column integraproduct.content
	 * @param content  the value for integraproduct.content
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column integraproduct.packing
	 * @return  the value of integraproduct.packing
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	public String getPacking() {
		return packing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column integraproduct.packing
	 * @param packing  the value for integraproduct.packing
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	public void setPacking(String packing) {
		this.packing = packing == null ? null : packing.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column integraproduct.afterservice
	 * @return  the value of integraproduct.afterservice
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	public String getAfterservice() {
		return afterservice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column integraproduct.afterservice
	 * @param afterservice  the value for integraproduct.afterservice
	 * @mbggenerated  Sun Sep 18 10:55:26 CST 2016
	 */
	public void setAfterservice(String afterservice) {
		this.afterservice = afterservice == null ? null : afterservice.trim();
	}
}