package com.yinlian.wssc.web.po;

import java.util.Date;

import data.ParseUtil;

public class Snews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.id
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.keyword
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.tag
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.title
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.tabloid
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String tabloid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ishead
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer ishead;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.isindex
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer isindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.isrecommend
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer isrecommend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.istop
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer istop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.author
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.src
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String src;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.createtime
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Date createtime;

	private String createtimetr;
	
	private String content;

	public String getCreatetimetr() {
		this.createtimetr = ParseUtil.parseDateToString(createtime, "yyyy-MM-dd HH:mm:ss");
		return createtimetr;
	}

	public void setCreatetimetr(String createtimetr) {
		this.createtimetr = createtimetr;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.state
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.cid
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ctype
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer ctype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.updatetime
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Date updatetime;

	private String updatetimetr;

	public String getUpdatetimetr() {
		this.updatetimetr = ParseUtil.parseDateToString(updatetime, "yyyy-MM-dd HH:mm:ss");
		return updatetimetr;
	}

	public void setUpdatetimetr(String updatetimetr) {
		this.updatetimetr = updatetimetr;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.imgurl
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String imgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.sort
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.yconut
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer yconut;

	private String url;

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex1
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private Integer ex1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex2
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String ex2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex3
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String ex3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex4
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String ex4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex5
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String ex5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex6
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String ex6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.ex7
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String ex7;

	private String province;

	private String city;

	private String area;

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.id
	 * 
	 * @return the value of s_news.id
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.id
	 * 
	 * @param id
	 *            the value for s_news.id
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.keyword
	 * 
	 * @return the value of s_news.keyword
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.keyword
	 * 
	 * @param keyword
	 *            the value for s_news.keyword
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword == null ? null : keyword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.tag
	 * 
	 * @return the value of s_news.tag
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.tag
	 * 
	 * @param tag
	 *            the value for s_news.tag
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setTag(String tag) {
		this.tag = tag == null ? null : tag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.title
	 * 
	 * @return the value of s_news.title
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.title
	 * 
	 * @param title
	 *            the value for s_news.title
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.tabloid
	 * 
	 * @return the value of s_news.tabloid
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getTabloid() {
		return tabloid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.tabloid
	 * 
	 * @param tabloid
	 *            the value for s_news.tabloid
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setTabloid(String tabloid) {
		this.tabloid = tabloid == null ? null : tabloid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ishead
	 * 
	 * @return the value of s_news.ishead
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getIshead() {
		return ishead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ishead
	 * 
	 * @param ishead
	 *            the value for s_news.ishead
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setIshead(Integer ishead) {
		this.ishead = ishead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.isindex
	 * 
	 * @return the value of s_news.isindex
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getIsindex() {
		return isindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.isindex
	 * 
	 * @param isindex
	 *            the value for s_news.isindex
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setIsindex(Integer isindex) {
		this.isindex = isindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.isrecommend
	 * 
	 * @return the value of s_news.isrecommend
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getIsrecommend() {
		return isrecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.isrecommend
	 * 
	 * @param isrecommend
	 *            the value for s_news.isrecommend
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setIsrecommend(Integer isrecommend) {
		this.isrecommend = isrecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.istop
	 * 
	 * @return the value of s_news.istop
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getIstop() {
		return istop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.istop
	 * 
	 * @param istop
	 *            the value for s_news.istop
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setIstop(Integer istop) {
		this.istop = istop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.author
	 * 
	 * @return the value of s_news.author
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.author
	 * 
	 * @param author
	 *            the value for s_news.author
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.src
	 * 
	 * @return the value of s_news.src
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getSrc() {
		return src;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.src
	 * 
	 * @param src
	 *            the value for s_news.src
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setSrc(String src) {
		this.src = src == null ? null : src.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.createtime
	 * 
	 * @return the value of s_news.createtime
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.createtime
	 * 
	 * @param createtime
	 *            the value for s_news.createtime
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.state
	 * 
	 * @return the value of s_news.state
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.state
	 * 
	 * @param state
	 *            the value for s_news.state
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.cid
	 * 
	 * @return the value of s_news.cid
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.cid
	 * 
	 * @param cid
	 *            the value for s_news.cid
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ctype
	 * 
	 * @return the value of s_news.ctype
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getCtype() {
		return ctype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ctype
	 * 
	 * @param ctype
	 *            the value for s_news.ctype
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setCtype(Integer ctype) {
		this.ctype = ctype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.updatetime
	 * 
	 * @return the value of s_news.updatetime
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.updatetime
	 * 
	 * @param updatetime
	 *            the value for s_news.updatetime
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.imgurl
	 * 
	 * @return the value of s_news.imgurl
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getImgurl() {
		return imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.imgurl
	 * 
	 * @param imgurl
	 *            the value for s_news.imgurl
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setImgurl(String imgurl) {
		this.imgurl = imgurl == null ? null : imgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.sort
	 * 
	 * @return the value of s_news.sort
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.sort
	 * 
	 * @param sort
	 *            the value for s_news.sort
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.yconut
	 * 
	 * @return the value of s_news.yconut
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getYconut() {
		return yconut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.yconut
	 * 
	 * @param yconut
	 *            the value for s_news.yconut
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setYconut(Integer yconut) {
		this.yconut = yconut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex1
	 * 
	 * @return the value of s_news.ex1
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public Integer getEx1() {
		return ex1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex1
	 * 
	 * @param ex1
	 *            the value for s_news.ex1
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx1(Integer ex1) {
		this.ex1 = ex1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex2
	 * 
	 * @return the value of s_news.ex2
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getEx2() {
		return ex2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex2
	 * 
	 * @param ex2
	 *            the value for s_news.ex2
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx2(String ex2) {
		this.ex2 = ex2 == null ? null : ex2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex3
	 * 
	 * @return the value of s_news.ex3
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getEx3() {
		return ex3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex3
	 * 
	 * @param ex3
	 *            the value for s_news.ex3
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx3(String ex3) {
		this.ex3 = ex3 == null ? null : ex3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex4
	 * 
	 * @return the value of s_news.ex4
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getEx4() {
		return ex4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex4
	 * 
	 * @param ex4
	 *            the value for s_news.ex4
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx4(String ex4) {
		this.ex4 = ex4 == null ? null : ex4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex5
	 * 
	 * @return the value of s_news.ex5
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getEx5() {
		return ex5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex5
	 * 
	 * @param ex5
	 *            the value for s_news.ex5
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx5(String ex5) {
		this.ex5 = ex5 == null ? null : ex5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex6
	 * 
	 * @return the value of s_news.ex6
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getEx6() {
		return ex6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex6
	 * 
	 * @param ex6
	 *            the value for s_news.ex6
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx6(String ex6) {
		this.ex6 = ex6 == null ? null : ex6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.ex7
	 * 
	 * @return the value of s_news.ex7
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getEx7() {
		return ex7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.ex7
	 * 
	 * @param ex7
	 *            the value for s_news.ex7
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setEx7(String ex7) {
		this.ex7 = ex7 == null ? null : ex7.trim();
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}
}