package com.yinlian.wssc.web.service;

import java.util.List;

import com.yinlian.api.app.dto.AlipayAppDto;
import com.yinlian.api.app.dto.IpsAppDto;
import com.yinlian.wssc.web.interceptor.PageBean;
import com.yinlian.wssc.web.po.Payconfig;
import com.yinlian.wssc.web.po.PayconfigExample;
import com.yinlian.wssc.web.util.Criteria;

public interface PayconfigService {


    /**删除支付配置
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id)throws Exception;

    /**添加支付配置
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int insert(Payconfig record)throws Exception;

    /**查询支付配置
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    List<Payconfig> selectByExample(PayconfigExample example)throws Exception;

    /**根据ID查询支付配置
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    Payconfig selectByPrimaryKey(Integer id)throws Exception;

    /**修改支付配置
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_config
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    int updateByPrimaryKey(Payconfig record)throws Exception;
    
    /**
     * 根据类型和使用平台查询支付配置
     * @param paytype
     * @param sites
     * @return
     * @throws Exception
     */
    Payconfig getByType(Integer paytype,Integer sites)throws Exception;
    
    /**
     * 获取支付配置列表
     * @param criteria
     * @param page
     * @param size
     * @return
     * @throws Exception
     */
   PageBean getListByPage(Criteria criteria,int page,int size)throws Exception;
   
   /**
    * 根据app支付配置
    * @param paytype
    * @param sites
    * @return
    * @throws Exception
    */
   AlipayAppDto getAppConfig()throws Exception;

   IpsAppDto getIpsConfig() throws Exception;
}
