package com.yinlian.wssc.web.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HighspecialtyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public HighspecialtyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andKidIsNull() {
			addCriterion("kid is null");
			return (Criteria) this;
		}

		public Criteria andKidIsNotNull() {
			addCriterion("kid is not null");
			return (Criteria) this;
		}

		public Criteria andKidEqualTo(Integer value) {
			addCriterion("kid =", value, "kid");
			return (Criteria) this;
		}

		public Criteria andKidNotEqualTo(Integer value) {
			addCriterion("kid <>", value, "kid");
			return (Criteria) this;
		}

		public Criteria andKidGreaterThan(Integer value) {
			addCriterion("kid >", value, "kid");
			return (Criteria) this;
		}

		public Criteria andKidGreaterThanOrEqualTo(Integer value) {
			addCriterion("kid >=", value, "kid");
			return (Criteria) this;
		}

		public Criteria andKidLessThan(Integer value) {
			addCriterion("kid <", value, "kid");
			return (Criteria) this;
		}

		public Criteria andKidLessThanOrEqualTo(Integer value) {
			addCriterion("kid <=", value, "kid");
			return (Criteria) this;
		}

		public Criteria andKidIn(List<Integer> values) {
			addCriterion("kid in", values, "kid");
			return (Criteria) this;
		}

		public Criteria andKidNotIn(List<Integer> values) {
			addCriterion("kid not in", values, "kid");
			return (Criteria) this;
		}

		public Criteria andKidBetween(Integer value1, Integer value2) {
			addCriterion("kid between", value1, value2, "kid");
			return (Criteria) this;
		}

		public Criteria andKidNotBetween(Integer value1, Integer value2) {
			addCriterion("kid not between", value1, value2, "kid");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createtime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createtime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createtime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createtime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createtime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createtime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createtime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createtime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createtime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createtime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createtime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createtime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andImgurlIsNull() {
			addCriterion("imgurl is null");
			return (Criteria) this;
		}

		public Criteria andImgurlIsNotNull() {
			addCriterion("imgurl is not null");
			return (Criteria) this;
		}

		public Criteria andImgurlEqualTo(String value) {
			addCriterion("imgurl =", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlNotEqualTo(String value) {
			addCriterion("imgurl <>", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlGreaterThan(String value) {
			addCriterion("imgurl >", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlGreaterThanOrEqualTo(String value) {
			addCriterion("imgurl >=", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlLessThan(String value) {
			addCriterion("imgurl <", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlLessThanOrEqualTo(String value) {
			addCriterion("imgurl <=", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlLike(String value) {
			addCriterion("imgurl like", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlNotLike(String value) {
			addCriterion("imgurl not like", value, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlIn(List<String> values) {
			addCriterion("imgurl in", values, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlNotIn(List<String> values) {
			addCriterion("imgurl not in", values, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlBetween(String value1, String value2) {
			addCriterion("imgurl between", value1, value2, "imgurl");
			return (Criteria) this;
		}

		public Criteria andImgurlNotBetween(String value1, String value2) {
			addCriterion("imgurl not between", value1, value2, "imgurl");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("sort is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("sort is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("sort =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("sort <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("sort >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("sort <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("sort <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("sort in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("sort not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("sort between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("sort not between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andEx1IsNull() {
			addCriterion("ex1 is null");
			return (Criteria) this;
		}

		public Criteria andEx1IsNotNull() {
			addCriterion("ex1 is not null");
			return (Criteria) this;
		}

		public Criteria andEx1EqualTo(Integer value) {
			addCriterion("ex1 =", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotEqualTo(Integer value) {
			addCriterion("ex1 <>", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1GreaterThan(Integer value) {
			addCriterion("ex1 >", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1GreaterThanOrEqualTo(Integer value) {
			addCriterion("ex1 >=", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1LessThan(Integer value) {
			addCriterion("ex1 <", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1LessThanOrEqualTo(Integer value) {
			addCriterion("ex1 <=", value, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1In(List<Integer> values) {
			addCriterion("ex1 in", values, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotIn(List<Integer> values) {
			addCriterion("ex1 not in", values, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1Between(Integer value1, Integer value2) {
			addCriterion("ex1 between", value1, value2, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx1NotBetween(Integer value1, Integer value2) {
			addCriterion("ex1 not between", value1, value2, "ex1");
			return (Criteria) this;
		}

		public Criteria andEx2IsNull() {
			addCriterion("ex2 is null");
			return (Criteria) this;
		}

		public Criteria andEx2IsNotNull() {
			addCriterion("ex2 is not null");
			return (Criteria) this;
		}

		public Criteria andEx2EqualTo(Integer value) {
			addCriterion("ex2 =", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotEqualTo(Integer value) {
			addCriterion("ex2 <>", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2GreaterThan(Integer value) {
			addCriterion("ex2 >", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2GreaterThanOrEqualTo(Integer value) {
			addCriterion("ex2 >=", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2LessThan(Integer value) {
			addCriterion("ex2 <", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2LessThanOrEqualTo(Integer value) {
			addCriterion("ex2 <=", value, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2In(List<Integer> values) {
			addCriterion("ex2 in", values, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotIn(List<Integer> values) {
			addCriterion("ex2 not in", values, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2Between(Integer value1, Integer value2) {
			addCriterion("ex2 between", value1, value2, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx2NotBetween(Integer value1, Integer value2) {
			addCriterion("ex2 not between", value1, value2, "ex2");
			return (Criteria) this;
		}

		public Criteria andEx3IsNull() {
			addCriterion("ex3 is null");
			return (Criteria) this;
		}

		public Criteria andEx3IsNotNull() {
			addCriterion("ex3 is not null");
			return (Criteria) this;
		}

		public Criteria andEx3EqualTo(String value) {
			addCriterion("ex3 =", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotEqualTo(String value) {
			addCriterion("ex3 <>", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3GreaterThan(String value) {
			addCriterion("ex3 >", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3GreaterThanOrEqualTo(String value) {
			addCriterion("ex3 >=", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3LessThan(String value) {
			addCriterion("ex3 <", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3LessThanOrEqualTo(String value) {
			addCriterion("ex3 <=", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3Like(String value) {
			addCriterion("ex3 like", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotLike(String value) {
			addCriterion("ex3 not like", value, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3In(List<String> values) {
			addCriterion("ex3 in", values, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotIn(List<String> values) {
			addCriterion("ex3 not in", values, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3Between(String value1, String value2) {
			addCriterion("ex3 between", value1, value2, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx3NotBetween(String value1, String value2) {
			addCriterion("ex3 not between", value1, value2, "ex3");
			return (Criteria) this;
		}

		public Criteria andEx4IsNull() {
			addCriterion("ex4 is null");
			return (Criteria) this;
		}

		public Criteria andEx4IsNotNull() {
			addCriterion("ex4 is not null");
			return (Criteria) this;
		}

		public Criteria andEx4EqualTo(String value) {
			addCriterion("ex4 =", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotEqualTo(String value) {
			addCriterion("ex4 <>", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4GreaterThan(String value) {
			addCriterion("ex4 >", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4GreaterThanOrEqualTo(String value) {
			addCriterion("ex4 >=", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4LessThan(String value) {
			addCriterion("ex4 <", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4LessThanOrEqualTo(String value) {
			addCriterion("ex4 <=", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4Like(String value) {
			addCriterion("ex4 like", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotLike(String value) {
			addCriterion("ex4 not like", value, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4In(List<String> values) {
			addCriterion("ex4 in", values, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotIn(List<String> values) {
			addCriterion("ex4 not in", values, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4Between(String value1, String value2) {
			addCriterion("ex4 between", value1, value2, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx4NotBetween(String value1, String value2) {
			addCriterion("ex4 not between", value1, value2, "ex4");
			return (Criteria) this;
		}

		public Criteria andEx5IsNull() {
			addCriterion("ex5 is null");
			return (Criteria) this;
		}

		public Criteria andEx5IsNotNull() {
			addCriterion("ex5 is not null");
			return (Criteria) this;
		}

		public Criteria andEx5EqualTo(String value) {
			addCriterion("ex5 =", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5NotEqualTo(String value) {
			addCriterion("ex5 <>", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5GreaterThan(String value) {
			addCriterion("ex5 >", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5GreaterThanOrEqualTo(String value) {
			addCriterion("ex5 >=", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5LessThan(String value) {
			addCriterion("ex5 <", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5LessThanOrEqualTo(String value) {
			addCriterion("ex5 <=", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5Like(String value) {
			addCriterion("ex5 like", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5NotLike(String value) {
			addCriterion("ex5 not like", value, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5In(List<String> values) {
			addCriterion("ex5 in", values, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5NotIn(List<String> values) {
			addCriterion("ex5 not in", values, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5Between(String value1, String value2) {
			addCriterion("ex5 between", value1, value2, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx5NotBetween(String value1, String value2) {
			addCriterion("ex5 not between", value1, value2, "ex5");
			return (Criteria) this;
		}

		public Criteria andEx6IsNull() {
			addCriterion("ex6 is null");
			return (Criteria) this;
		}

		public Criteria andEx6IsNotNull() {
			addCriterion("ex6 is not null");
			return (Criteria) this;
		}

		public Criteria andEx6EqualTo(String value) {
			addCriterion("ex6 =", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6NotEqualTo(String value) {
			addCriterion("ex6 <>", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6GreaterThan(String value) {
			addCriterion("ex6 >", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6GreaterThanOrEqualTo(String value) {
			addCriterion("ex6 >=", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6LessThan(String value) {
			addCriterion("ex6 <", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6LessThanOrEqualTo(String value) {
			addCriterion("ex6 <=", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6Like(String value) {
			addCriterion("ex6 like", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6NotLike(String value) {
			addCriterion("ex6 not like", value, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6In(List<String> values) {
			addCriterion("ex6 in", values, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6NotIn(List<String> values) {
			addCriterion("ex6 not in", values, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6Between(String value1, String value2) {
			addCriterion("ex6 between", value1, value2, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx6NotBetween(String value1, String value2) {
			addCriterion("ex6 not between", value1, value2, "ex6");
			return (Criteria) this;
		}

		public Criteria andEx7IsNull() {
			addCriterion("ex7 is null");
			return (Criteria) this;
		}

		public Criteria andEx7IsNotNull() {
			addCriterion("ex7 is not null");
			return (Criteria) this;
		}

		public Criteria andEx7EqualTo(String value) {
			addCriterion("ex7 =", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7NotEqualTo(String value) {
			addCriterion("ex7 <>", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7GreaterThan(String value) {
			addCriterion("ex7 >", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7GreaterThanOrEqualTo(String value) {
			addCriterion("ex7 >=", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7LessThan(String value) {
			addCriterion("ex7 <", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7LessThanOrEqualTo(String value) {
			addCriterion("ex7 <=", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7Like(String value) {
			addCriterion("ex7 like", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7NotLike(String value) {
			addCriterion("ex7 not like", value, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7In(List<String> values) {
			addCriterion("ex7 in", values, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7NotIn(List<String> values) {
			addCriterion("ex7 not in", values, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7Between(String value1, String value2) {
			addCriterion("ex7 between", value1, value2, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx7NotBetween(String value1, String value2) {
			addCriterion("ex7 not between", value1, value2, "ex7");
			return (Criteria) this;
		}

		public Criteria andEx8IsNull() {
			addCriterion("ex8 is null");
			return (Criteria) this;
		}

		public Criteria andEx8IsNotNull() {
			addCriterion("ex8 is not null");
			return (Criteria) this;
		}

		public Criteria andEx8EqualTo(String value) {
			addCriterion("ex8 =", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8NotEqualTo(String value) {
			addCriterion("ex8 <>", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8GreaterThan(String value) {
			addCriterion("ex8 >", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8GreaterThanOrEqualTo(String value) {
			addCriterion("ex8 >=", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8LessThan(String value) {
			addCriterion("ex8 <", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8LessThanOrEqualTo(String value) {
			addCriterion("ex8 <=", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8Like(String value) {
			addCriterion("ex8 like", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8NotLike(String value) {
			addCriterion("ex8 not like", value, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8In(List<String> values) {
			addCriterion("ex8 in", values, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8NotIn(List<String> values) {
			addCriterion("ex8 not in", values, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8Between(String value1, String value2) {
			addCriterion("ex8 between", value1, value2, "ex8");
			return (Criteria) this;
		}

		public Criteria andEx8NotBetween(String value1, String value2) {
			addCriterion("ex8 not between", value1, value2, "ex8");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table highspecialty
	 * @mbggenerated  Wed Sep 21 15:08:35 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table highspecialty
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 21 14:36:19 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}