package com.yinlian.wssc.web.po;

public class Hotcity {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column hotcity.id
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column hotcity.code
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column hotcity.name
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column hotcity.tabloid
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	private String tabloid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column hotcity.sort
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	private Integer sort;

	private String pcode;
	
	
	private String imgurl;

	public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	public String getPcode() {
		return pcode;
	}

	public void setPcode(String pcode) {
		this.pcode = pcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hotcity.id
	 *
	 * @return the value of hotcity.id
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hotcity.id
	 *
	 * @param id
	 *            the value for hotcity.id
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hotcity.code
	 *
	 * @return the value of hotcity.code
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hotcity.code
	 *
	 * @param code
	 *            the value for hotcity.code
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hotcity.name
	 *
	 * @return the value of hotcity.name
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hotcity.name
	 *
	 * @param name
	 *            the value for hotcity.name
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hotcity.tabloid
	 *
	 * @return the value of hotcity.tabloid
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public String getTabloid() {
		return tabloid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hotcity.tabloid
	 *
	 * @param tabloid
	 *            the value for hotcity.tabloid
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public void setTabloid(String tabloid) {
		this.tabloid = tabloid == null ? null : tabloid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hotcity.sort
	 *
	 * @return the value of hotcity.sort
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hotcity.sort
	 *
	 * @param sort
	 *            the value for hotcity.sort
	 *
	 * @mbggenerated Wed Sep 21 14:43:02 CST 2016
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}