package com.yinlian.wssc.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yinlian.wssc.web.po.Highspecialty;
import com.yinlian.wssc.web.po.HighspecialtyExample;
import com.yinlian.wssc.web.po.V_Hp_Sku;
import com.yinlian.wssc.web.util.PageBeanUtil;

public interface HighspecialtyMapper {

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int countByExample(HighspecialtyExample example);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int deleteByExample(HighspecialtyExample example);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int insert(Highspecialty record);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int insertSelective(Highspecialty record);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	List<Highspecialty> selectByExample(HighspecialtyExample example);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	Highspecialty selectByPrimaryKey(Integer id);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int updateByExampleSelective(@Param("record") Highspecialty record, @Param("example") HighspecialtyExample example);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int updateByExample(@Param("record") Highspecialty record, @Param("example") HighspecialtyExample example);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int updateByPrimaryKeySelective(Highspecialty record);

	/**
	 * <<<<<<< .mine This method was generated by MyBatis Generator. This method
	 * corresponds to the database table highspecialty
	 * 
	 * @mbggenerated Wed Sep 21 14:42:47 CST 2016 ======= This method was
	 *               generated by MyBatis Generator. This method corresponds to
	 *               the database table highspecialty
	 * @mbggenerated Wed Sep 21 15:08:35 CST 2016 >>>>>>> .r948
	 */
	int updateByPrimaryKey(Highspecialty record);

	List<V_Hp_Sku> getListPage(PageBeanUtil pageBeanUtil) throws Exception;

	int setType(Integer id, Integer type) throws Exception;

	V_Hp_Sku selVById(Integer id) throws Exception;

	List<Highspecialty> getByRecommend() throws Exception;

	List<V_Hp_Sku> getapplistPage(PageBeanUtil pageBeanUtil) throws Exception;

}