package com.yinlian.wssc.web.po;

public class SnewsWithBLOBs extends Snews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.subtitle
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String subtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_news.content
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.subtitle
	 * 
	 * @return the value of s_news.subtitle
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getSubtitle() {
		return subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.subtitle
	 * 
	 * @param subtitle
	 *            the value for s_news.subtitle
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_news.content
	 * 
	 * @return the value of s_news.content
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_news.content
	 * 
	 * @param content
	 *            the value for s_news.content
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}