package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.web.dto.NewsProDto;
import com.yinlian.wssc.web.po.NewsProduct;
import com.yinlian.wssc.web.po.NewsProductExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int countByExample(NewsProductExample example)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int deleteByExample(NewsProductExample example)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int deleteByPrimaryKey(Integer id)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int insert(NewsProduct record)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int insertSelective(NewsProduct record)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	List<NewsProduct> selectByExample(NewsProductExample example)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	NewsProduct selectByPrimaryKey(Integer id)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int updateByExampleSelective(@Param("record") NewsProduct record, @Param("example") NewsProductExample example)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int updateByExample(@Param("record") NewsProduct record, @Param("example") NewsProductExample example)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int updateByPrimaryKeySelective(NewsProduct record)throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	int updateByPrimaryKey(NewsProduct record)throws Exception;

	/**
	 * 分页
	 * @param beanUtil
	 * @return
	 * @throws Exception
	 */
	List<NewsProDto> selectByPage(PageBeanUtil beanUtil) throws Exception;

	/**
	 * 获取商品
	 * @return
	 * @throws Exception
	 */
	List<com.yinlian.pc.dto.NewsProDto> selectProPcList(Integer newsid)throws Exception;
}