package com.yinlian.wssc.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yinlian.wssc.web.po.SnewsRImgs;
import com.yinlian.wssc.web.po.SnewsRImgsExample;

public interface SnewsRImgsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int countByExample(SnewsRImgsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int deleteByExample(SnewsRImgsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int insert(SnewsRImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int insertSelective(SnewsRImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	List<SnewsRImgs> selectByExample(SnewsRImgsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	SnewsRImgs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SnewsRImgs record, @Param("example") SnewsRImgsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int updateByExample(@Param("record") SnewsRImgs record, @Param("example") SnewsRImgsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int updateByPrimaryKeySelective(SnewsRImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_r_imgs
	 *
	 * @mbggenerated Wed Sep 14 13:32:17 CST 2016
	 */
	int updateByPrimaryKey(SnewsRImgs record);

	int delBySnewsid(Integer id) throws Exception;

	List<SnewsRImgs> selRNewsImgBySid(Integer sid) throws Exception;

}