package com.yinlian.wssc.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yinlian.app.dto.NewsBaseDto;
import com.yinlian.wssc.web.po.Snews;
import com.yinlian.wssc.web.po.SnewsExample;
import com.yinlian.wssc.web.po.SnewsWithBLOBs;
import com.yinlian.wssc.web.util.PageBeanUtil;

public interface SnewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int countByExample(SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int deleteByExample(SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int insert(SnewsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int insertSelective(SnewsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	List<SnewsWithBLOBs> selectByExampleWithBLOBs(SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	List<Snews> selectByExample(SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	SnewsWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SnewsWithBLOBs record, @Param("example") SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") SnewsWithBLOBs record, @Param("example") SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int updateByExample(@Param("record") Snews record, @Param("example") SnewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int updateByPrimaryKeySelective(SnewsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(SnewsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news
	 * 
	 * @mbggenerated Tue Sep 06 10:42:51 CST 2016
	 */
	int updateByPrimaryKey(Snews record);

	SnewsWithBLOBs selSingle(Integer ctype);

	List<SnewsWithBLOBs> querySlistPage(PageBeanUtil pageBeanUtil) throws Exception;

	int setstate(Integer id, Integer state) throws Exception;

	int sethead(Integer id, Integer head) throws Exception;

	int setindex(Integer id, Integer index) throws Exception;

	int setrecommend(Integer id, Integer recommend) throws Exception;

	int settop(Integer id, Integer top) throws Exception;

	List<NewsBaseDto> getapplistPage(PageBeanUtil pageBeanUtil) throws Exception;

	SnewsWithBLOBs getById(Integer id) throws Exception;

	List<Snews> getByRecommend()throws Exception;
	
	List<Snews> getProvinceList()throws Exception;
	
	List<SnewsWithBLOBs> selectByNewsCid(Integer cid)throws Exception;
	
	List<SnewsWithBLOBs> selectByNewsCtype(Integer ctype)throws Exception;
	
	List<Snews> getProvincebyCode(Integer code)throws Exception;
}