package com.yinlian.wssc.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yinlian.wssc.web.po.SnewsImg;
import com.yinlian.wssc.web.po.SnewsImgExample;
import com.yinlian.wssc.web.po.SnewsImgWithBLOBs;
import com.yinlian.wssc.web.util.PageBeanUtil;

public interface SnewsImgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int countByExample(SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int deleteByExample(SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int insert(SnewsImgWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int insertSelective(SnewsImgWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	List<SnewsImgWithBLOBs> selectByExampleWithBLOBs(SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	List<SnewsImg> selectByExample(SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	SnewsImgWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SnewsImgWithBLOBs record, @Param("example") SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") SnewsImgWithBLOBs record, @Param("example") SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int updateByExample(@Param("record") SnewsImg record, @Param("example") SnewsImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int updateByPrimaryKeySelective(SnewsImgWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(SnewsImgWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_news_img
	 * 
	 * @mbggenerated Wed Sep 07 10:55:33 CST 2016
	 */
	int updateByPrimaryKey(SnewsImg record);

	List<SnewsImgWithBLOBs> queryNewsImgPage(PageBeanUtil pageBeanUtil) throws Exception;

	int setstate(Integer id, Integer state) throws Exception;

	int sethead(Integer id, Integer head) throws Exception;

	int setindex(Integer id, Integer index) throws Exception;

	int setrecommend(Integer id, Integer recommend) throws Exception;

	int settop(Integer id, Integer top) throws Exception;

}