package com.yinlian.wssc.web.po;

import java.util.Date;

public class login_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.ID
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.UserID
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.UserName
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.LoginTime
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.Ip
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.LoginAddress
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private String loginaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.LoginType
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private Integer logintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.Result
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private Boolean result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.Description
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.ID
     *
     * @return the value of login_info.ID
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.ID
     *
     * @param id the value for login_info.ID
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.UserID
     *
     * @return the value of login_info.UserID
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.UserID
     *
     * @param userid the value for login_info.UserID
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.UserName
     *
     * @return the value of login_info.UserName
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.UserName
     *
     * @param username the value for login_info.UserName
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.LoginTime
     *
     * @return the value of login_info.LoginTime
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.LoginTime
     *
     * @param logintime the value for login_info.LoginTime
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.Ip
     *
     * @return the value of login_info.Ip
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.Ip
     *
     * @param ip the value for login_info.Ip
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.LoginAddress
     *
     * @return the value of login_info.LoginAddress
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public String getLoginaddress() {
        return loginaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.LoginAddress
     *
     * @param loginaddress the value for login_info.LoginAddress
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setLoginaddress(String loginaddress) {
        this.loginaddress = loginaddress == null ? null : loginaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.LoginType
     *
     * @return the value of login_info.LoginType
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public Integer getLogintype() {
        return logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.LoginType
     *
     * @param logintype the value for login_info.LoginType
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setLogintype(Integer logintype) {
        this.logintype = logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.Result
     *
     * @return the value of login_info.Result
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.Result
     *
     * @param result the value for login_info.Result
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setResult(Boolean result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.Description
     *
     * @return the value of login_info.Description
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.Description
     *
     * @param description the value for login_info.Description
     *
     * @mbggenerated Fri Jun 24 15:54:43 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}