package com.yinlian.wssc.web.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class NewsProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public NewsProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNewsidIsNull() {
			addCriterion("NewsID is null");
			return (Criteria) this;
		}

		public Criteria andNewsidIsNotNull() {
			addCriterion("NewsID is not null");
			return (Criteria) this;
		}

		public Criteria andNewsidEqualTo(Integer value) {
			addCriterion("NewsID =", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidNotEqualTo(Integer value) {
			addCriterion("NewsID <>", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidGreaterThan(Integer value) {
			addCriterion("NewsID >", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidGreaterThanOrEqualTo(Integer value) {
			addCriterion("NewsID >=", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidLessThan(Integer value) {
			addCriterion("NewsID <", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidLessThanOrEqualTo(Integer value) {
			addCriterion("NewsID <=", value, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidIn(List<Integer> values) {
			addCriterion("NewsID in", values, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidNotIn(List<Integer> values) {
			addCriterion("NewsID not in", values, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidBetween(Integer value1, Integer value2) {
			addCriterion("NewsID between", value1, value2, "newsid");
			return (Criteria) this;
		}

		public Criteria andNewsidNotBetween(Integer value1, Integer value2) {
			addCriterion("NewsID not between", value1, value2, "newsid");
			return (Criteria) this;
		}

		public Criteria andSpuidIsNull() {
			addCriterion("SpuID is null");
			return (Criteria) this;
		}

		public Criteria andSpuidIsNotNull() {
			addCriterion("SpuID is not null");
			return (Criteria) this;
		}

		public Criteria andSpuidEqualTo(Integer value) {
			addCriterion("SpuID =", value, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidNotEqualTo(Integer value) {
			addCriterion("SpuID <>", value, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidGreaterThan(Integer value) {
			addCriterion("SpuID >", value, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidGreaterThanOrEqualTo(Integer value) {
			addCriterion("SpuID >=", value, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidLessThan(Integer value) {
			addCriterion("SpuID <", value, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidLessThanOrEqualTo(Integer value) {
			addCriterion("SpuID <=", value, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidIn(List<Integer> values) {
			addCriterion("SpuID in", values, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidNotIn(List<Integer> values) {
			addCriterion("SpuID not in", values, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidBetween(Integer value1, Integer value2) {
			addCriterion("SpuID between", value1, value2, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpuidNotBetween(Integer value1, Integer value2) {
			addCriterion("SpuID not between", value1, value2, "spuid");
			return (Criteria) this;
		}

		public Criteria andSpunameIsNull() {
			addCriterion("SpuName is null");
			return (Criteria) this;
		}

		public Criteria andSpunameIsNotNull() {
			addCriterion("SpuName is not null");
			return (Criteria) this;
		}

		public Criteria andSpunameEqualTo(String value) {
			addCriterion("SpuName =", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameNotEqualTo(String value) {
			addCriterion("SpuName <>", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameGreaterThan(String value) {
			addCriterion("SpuName >", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameGreaterThanOrEqualTo(String value) {
			addCriterion("SpuName >=", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameLessThan(String value) {
			addCriterion("SpuName <", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameLessThanOrEqualTo(String value) {
			addCriterion("SpuName <=", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameLike(String value) {
			addCriterion("SpuName like", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameNotLike(String value) {
			addCriterion("SpuName not like", value, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameIn(List<String> values) {
			addCriterion("SpuName in", values, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameNotIn(List<String> values) {
			addCriterion("SpuName not in", values, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameBetween(String value1, String value2) {
			addCriterion("SpuName between", value1, value2, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpunameNotBetween(String value1, String value2) {
			addCriterion("SpuName not between", value1, value2, "spuname");
			return (Criteria) this;
		}

		public Criteria andSpupriceIsNull() {
			addCriterion("SpuPrice is null");
			return (Criteria) this;
		}

		public Criteria andSpupriceIsNotNull() {
			addCriterion("SpuPrice is not null");
			return (Criteria) this;
		}

		public Criteria andSpupriceEqualTo(BigDecimal value) {
			addCriterion("SpuPrice =", value, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceNotEqualTo(BigDecimal value) {
			addCriterion("SpuPrice <>", value, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceGreaterThan(BigDecimal value) {
			addCriterion("SpuPrice >", value, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SpuPrice >=", value, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceLessThan(BigDecimal value) {
			addCriterion("SpuPrice <", value, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SpuPrice <=", value, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceIn(List<BigDecimal> values) {
			addCriterion("SpuPrice in", values, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceNotIn(List<BigDecimal> values) {
			addCriterion("SpuPrice not in", values, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SpuPrice between", value1, value2, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpupriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SpuPrice not between", value1, value2, "spuprice");
			return (Criteria) this;
		}

		public Criteria andSpuimgIsNull() {
			addCriterion("SpuImg is null");
			return (Criteria) this;
		}

		public Criteria andSpuimgIsNotNull() {
			addCriterion("SpuImg is not null");
			return (Criteria) this;
		}

		public Criteria andSpuimgEqualTo(String value) {
			addCriterion("SpuImg =", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgNotEqualTo(String value) {
			addCriterion("SpuImg <>", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgGreaterThan(String value) {
			addCriterion("SpuImg >", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgGreaterThanOrEqualTo(String value) {
			addCriterion("SpuImg >=", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgLessThan(String value) {
			addCriterion("SpuImg <", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgLessThanOrEqualTo(String value) {
			addCriterion("SpuImg <=", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgLike(String value) {
			addCriterion("SpuImg like", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgNotLike(String value) {
			addCriterion("SpuImg not like", value, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgIn(List<String> values) {
			addCriterion("SpuImg in", values, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgNotIn(List<String> values) {
			addCriterion("SpuImg not in", values, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgBetween(String value1, String value2) {
			addCriterion("SpuImg between", value1, value2, "spuimg");
			return (Criteria) this;
		}

		public Criteria andSpuimgNotBetween(String value1, String value2) {
			addCriterion("SpuImg not between", value1, value2, "spuimg");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("Type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("Type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("Type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("Type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("Type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("Type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("Type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("Type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("Type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("Type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("Type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("Type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andOrderbyIsNull() {
			addCriterion("OrderBy is null");
			return (Criteria) this;
		}

		public Criteria andOrderbyIsNotNull() {
			addCriterion("OrderBy is not null");
			return (Criteria) this;
		}

		public Criteria andOrderbyEqualTo(Integer value) {
			addCriterion("OrderBy =", value, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyNotEqualTo(Integer value) {
			addCriterion("OrderBy <>", value, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyGreaterThan(Integer value) {
			addCriterion("OrderBy >", value, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyGreaterThanOrEqualTo(Integer value) {
			addCriterion("OrderBy >=", value, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyLessThan(Integer value) {
			addCriterion("OrderBy <", value, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyLessThanOrEqualTo(Integer value) {
			addCriterion("OrderBy <=", value, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyIn(List<Integer> values) {
			addCriterion("OrderBy in", values, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyNotIn(List<Integer> values) {
			addCriterion("OrderBy not in", values, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyBetween(Integer value1, Integer value2) {
			addCriterion("OrderBy between", value1, value2, "orderby");
			return (Criteria) this;
		}

		public Criteria andOrderbyNotBetween(Integer value1, Integer value2) {
			addCriterion("OrderBy not between", value1, value2, "orderby");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table news_product
	 * @mbggenerated  Tue Dec 06 08:58:01 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_product
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 06 08:57:52 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}