package com.yinlian.wssc.web.po;

import java.util.Date;

import com.yinlian.wssc.web.util.DateUtil;

public class Payconfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.id
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.partner
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.sellerid
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.private_key
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String privateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.sign_type
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.notify_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.success_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String successUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.fail_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String failUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.payment_type
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.mername
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String mername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.actionUrl
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String actionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.currency
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.lang
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.retencode
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer retencode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.orderencode
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer orderencode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.billvalidity
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer billvalidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.paytype
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.version
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.iscredit
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer iscredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.bankno
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.producttype
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.anti_phishing_key
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String antiPhishingKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.exter_invoke_ip
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private String exterInvokeIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.createtime
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.createuserid
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_config.status
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    private Integer status;
    
    private Integer sites;

    private String msgid;
    
    private Integer rettype;
    
    private String publicKey;
    
    private String appid;
    
    public String getPublicKey() {
		return publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	private String createtimestr;
    
    public String getMsgid() {
		return msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	public Integer getRettype() {
		return rettype;
	}

	public void setRettype(Integer rettype) {
		this.rettype = rettype;
	}

	public String getCreatetimestr() {
		return DateUtil.dateConvert(this.createtime);
	}

	public void setCreatetimestr(String createtimestr) {
		this.createtimestr = createtimestr;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.id
     *
     * @return the value of pay_config.id
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.id
     *
     * @param id the value for pay_config.id
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.partner
     *
     * @return the value of pay_config.partner
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.partner
     *
     * @param partner the value for pay_config.partner
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.sellerid
     *
     * @return the value of pay_config.sellerid
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.sellerid
     *
     * @param sellerid the value for pay_config.sellerid
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid == null ? null : sellerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.private_key
     *
     * @return the value of pay_config.private_key
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.private_key
     *
     * @param privateKey the value for pay_config.private_key
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.sign_type
     *
     * @return the value of pay_config.sign_type
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.sign_type
     *
     * @param signType the value for pay_config.sign_type
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.notify_url
     *
     * @return the value of pay_config.notify_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.notify_url
     *
     * @param notifyUrl the value for pay_config.notify_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.success_url
     *
     * @return the value of pay_config.success_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getSuccessUrl() {
        return successUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.success_url
     *
     * @param successUrl the value for pay_config.success_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setSuccessUrl(String successUrl) {
        this.successUrl = successUrl == null ? null : successUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.fail_url
     *
     * @return the value of pay_config.fail_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getFailUrl() {
        return failUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.fail_url
     *
     * @param failUrl the value for pay_config.fail_url
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setFailUrl(String failUrl) {
        this.failUrl = failUrl == null ? null : failUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.payment_type
     *
     * @return the value of pay_config.payment_type
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.payment_type
     *
     * @param paymentType the value for pay_config.payment_type
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.mername
     *
     * @return the value of pay_config.mername
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getMername() {
        return mername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.mername
     *
     * @param mername the value for pay_config.mername
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setMername(String mername) {
        this.mername = mername == null ? null : mername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.actionUrl
     *
     * @return the value of pay_config.actionUrl
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getActionurl() {
        return actionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.actionUrl
     *
     * @param actionurl the value for pay_config.actionUrl
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setActionurl(String actionurl) {
        this.actionurl = actionurl == null ? null : actionurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.currency
     *
     * @return the value of pay_config.currency
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.currency
     *
     * @param currency the value for pay_config.currency
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setCurrency(Integer currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.lang
     *
     * @return the value of pay_config.lang
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.lang
     *
     * @param lang the value for pay_config.lang
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.retencode
     *
     * @return the value of pay_config.retencode
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getRetencode() {
        return retencode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.retencode
     *
     * @param retencode the value for pay_config.retencode
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setRetencode(Integer retencode) {
        this.retencode = retencode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.orderencode
     *
     * @return the value of pay_config.orderencode
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getOrderencode() {
        return orderencode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.orderencode
     *
     * @param orderencode the value for pay_config.orderencode
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setOrderencode(Integer orderencode) {
        this.orderencode = orderencode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.billvalidity
     *
     * @return the value of pay_config.billvalidity
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getBillvalidity() {
        return billvalidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.billvalidity
     *
     * @param billvalidity the value for pay_config.billvalidity
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setBillvalidity(Integer billvalidity) {
        this.billvalidity = billvalidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.paytype
     *
     * @return the value of pay_config.paytype
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.paytype
     *
     * @param paytype the value for pay_config.paytype
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.version
     *
     * @return the value of pay_config.version
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.version
     *
     * @param version the value for pay_config.version
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.iscredit
     *
     * @return the value of pay_config.iscredit
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getIscredit() {
        return iscredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.iscredit
     *
     * @param iscredit the value for pay_config.iscredit
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setIscredit(Integer iscredit) {
        this.iscredit = iscredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.bankno
     *
     * @return the value of pay_config.bankno
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.bankno
     *
     * @param bankno the value for pay_config.bankno
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.producttype
     *
     * @return the value of pay_config.producttype
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.producttype
     *
     * @param producttype the value for pay_config.producttype
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setProducttype(Integer producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.anti_phishing_key
     *
     * @return the value of pay_config.anti_phishing_key
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getAntiPhishingKey() {
        return antiPhishingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.anti_phishing_key
     *
     * @param antiPhishingKey the value for pay_config.anti_phishing_key
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setAntiPhishingKey(String antiPhishingKey) {
        this.antiPhishingKey = antiPhishingKey == null ? null : antiPhishingKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.exter_invoke_ip
     *
     * @return the value of pay_config.exter_invoke_ip
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public String getExterInvokeIp() {
        return exterInvokeIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.exter_invoke_ip
     *
     * @param exterInvokeIp the value for pay_config.exter_invoke_ip
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setExterInvokeIp(String exterInvokeIp) {
        this.exterInvokeIp = exterInvokeIp == null ? null : exterInvokeIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.createtime
     *
     * @return the value of pay_config.createtime
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.createtime
     *
     * @param createtime the value for pay_config.createtime
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.createuserid
     *
     * @return the value of pay_config.createuserid
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.createuserid
     *
     * @param createuserid the value for pay_config.createuserid
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_config.status
     *
     * @return the value of pay_config.status
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_config.status
     *
     * @param status the value for pay_config.status
     *
     * @mbggenerated Mon Jun 20 17:09:48 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Integer getSites() {
		return sites;
	}

	public void setSites(Integer sites) {
		this.sites = sites;
	}

	public String getAppid() {
		return appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}
}