package com.yinlian.wssc.web.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class showuserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public showuserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShowidIsNull() {
            addCriterion("ShowID is null");
            return (Criteria) this;
        }

        public Criteria andShowidIsNotNull() {
            addCriterion("ShowID is not null");
            return (Criteria) this;
        }

        public Criteria andShowidEqualTo(Integer value) {
            addCriterion("ShowID =", value, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidNotEqualTo(Integer value) {
            addCriterion("ShowID <>", value, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidGreaterThan(Integer value) {
            addCriterion("ShowID >", value, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ShowID >=", value, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidLessThan(Integer value) {
            addCriterion("ShowID <", value, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidLessThanOrEqualTo(Integer value) {
            addCriterion("ShowID <=", value, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidIn(List<Integer> values) {
            addCriterion("ShowID in", values, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidNotIn(List<Integer> values) {
            addCriterion("ShowID not in", values, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidBetween(Integer value1, Integer value2) {
            addCriterion("ShowID between", value1, value2, "showid");
            return (Criteria) this;
        }

        public Criteria andShowidNotBetween(Integer value1, Integer value2) {
            addCriterion("ShowID not between", value1, value2, "showid");
            return (Criteria) this;
        }

        public Criteria andShowtitleIsNull() {
            addCriterion("ShowTitle is null");
            return (Criteria) this;
        }

        public Criteria andShowtitleIsNotNull() {
            addCriterion("ShowTitle is not null");
            return (Criteria) this;
        }

        public Criteria andShowtitleEqualTo(String value) {
            addCriterion("ShowTitle =", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleNotEqualTo(String value) {
            addCriterion("ShowTitle <>", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleGreaterThan(String value) {
            addCriterion("ShowTitle >", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleGreaterThanOrEqualTo(String value) {
            addCriterion("ShowTitle >=", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleLessThan(String value) {
            addCriterion("ShowTitle <", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleLessThanOrEqualTo(String value) {
            addCriterion("ShowTitle <=", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleLike(String value) {
            addCriterion("ShowTitle like", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleNotLike(String value) {
            addCriterion("ShowTitle not like", value, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleIn(List<String> values) {
            addCriterion("ShowTitle in", values, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleNotIn(List<String> values) {
            addCriterion("ShowTitle not in", values, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleBetween(String value1, String value2) {
            addCriterion("ShowTitle between", value1, value2, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowtitleNotBetween(String value1, String value2) {
            addCriterion("ShowTitle not between", value1, value2, "showtitle");
            return (Criteria) this;
        }

        public Criteria andShowuseridIsNull() {
            addCriterion("ShowUserID is null");
            return (Criteria) this;
        }

        public Criteria andShowuseridIsNotNull() {
            addCriterion("ShowUserID is not null");
            return (Criteria) this;
        }

        public Criteria andShowuseridEqualTo(Integer value) {
            addCriterion("ShowUserID =", value, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridNotEqualTo(Integer value) {
            addCriterion("ShowUserID <>", value, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridGreaterThan(Integer value) {
            addCriterion("ShowUserID >", value, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ShowUserID >=", value, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridLessThan(Integer value) {
            addCriterion("ShowUserID <", value, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridLessThanOrEqualTo(Integer value) {
            addCriterion("ShowUserID <=", value, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridIn(List<Integer> values) {
            addCriterion("ShowUserID in", values, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridNotIn(List<Integer> values) {
            addCriterion("ShowUserID not in", values, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridBetween(Integer value1, Integer value2) {
            addCriterion("ShowUserID between", value1, value2, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShowuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("ShowUserID not between", value1, value2, "showuserid");
            return (Criteria) this;
        }

        public Criteria andShownicknameIsNull() {
            addCriterion("ShowNickName is null");
            return (Criteria) this;
        }

        public Criteria andShownicknameIsNotNull() {
            addCriterion("ShowNickName is not null");
            return (Criteria) this;
        }

        public Criteria andShownicknameEqualTo(String value) {
            addCriterion("ShowNickName =", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameNotEqualTo(String value) {
            addCriterion("ShowNickName <>", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameGreaterThan(String value) {
            addCriterion("ShowNickName >", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameGreaterThanOrEqualTo(String value) {
            addCriterion("ShowNickName >=", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameLessThan(String value) {
            addCriterion("ShowNickName <", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameLessThanOrEqualTo(String value) {
            addCriterion("ShowNickName <=", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameLike(String value) {
            addCriterion("ShowNickName like", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameNotLike(String value) {
            addCriterion("ShowNickName not like", value, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameIn(List<String> values) {
            addCriterion("ShowNickName in", values, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameNotIn(List<String> values) {
            addCriterion("ShowNickName not in", values, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameBetween(String value1, String value2) {
            addCriterion("ShowNickName between", value1, value2, "shownickname");
            return (Criteria) this;
        }

        public Criteria andShownicknameNotBetween(String value1, String value2) {
            addCriterion("ShowNickName not between", value1, value2, "shownickname");
            return (Criteria) this;
        }

        public Criteria andLikeuseridIsNull() {
            addCriterion("LikeUserID is null");
            return (Criteria) this;
        }

        public Criteria andLikeuseridIsNotNull() {
            addCriterion("LikeUserID is not null");
            return (Criteria) this;
        }

        public Criteria andLikeuseridEqualTo(Integer value) {
            addCriterion("LikeUserID =", value, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridNotEqualTo(Integer value) {
            addCriterion("LikeUserID <>", value, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridGreaterThan(Integer value) {
            addCriterion("LikeUserID >", value, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("LikeUserID >=", value, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridLessThan(Integer value) {
            addCriterion("LikeUserID <", value, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridLessThanOrEqualTo(Integer value) {
            addCriterion("LikeUserID <=", value, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridIn(List<Integer> values) {
            addCriterion("LikeUserID in", values, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridNotIn(List<Integer> values) {
            addCriterion("LikeUserID not in", values, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridBetween(Integer value1, Integer value2) {
            addCriterion("LikeUserID between", value1, value2, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikeuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("LikeUserID not between", value1, value2, "likeuserid");
            return (Criteria) this;
        }

        public Criteria andLikenicknameIsNull() {
            addCriterion("LikeNickName is null");
            return (Criteria) this;
        }

        public Criteria andLikenicknameIsNotNull() {
            addCriterion("LikeNickName is not null");
            return (Criteria) this;
        }

        public Criteria andLikenicknameEqualTo(String value) {
            addCriterion("LikeNickName =", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameNotEqualTo(String value) {
            addCriterion("LikeNickName <>", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameGreaterThan(String value) {
            addCriterion("LikeNickName >", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameGreaterThanOrEqualTo(String value) {
            addCriterion("LikeNickName >=", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameLessThan(String value) {
            addCriterion("LikeNickName <", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameLessThanOrEqualTo(String value) {
            addCriterion("LikeNickName <=", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameLike(String value) {
            addCriterion("LikeNickName like", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameNotLike(String value) {
            addCriterion("LikeNickName not like", value, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameIn(List<String> values) {
            addCriterion("LikeNickName in", values, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameNotIn(List<String> values) {
            addCriterion("LikeNickName not in", values, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameBetween(String value1, String value2) {
            addCriterion("LikeNickName between", value1, value2, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLikenicknameNotBetween(String value1, String value2) {
            addCriterion("LikeNickName not between", value1, value2, "likenickname");
            return (Criteria) this;
        }

        public Criteria andLiketimeIsNull() {
            addCriterion("LikeTime is null");
            return (Criteria) this;
        }

        public Criteria andLiketimeIsNotNull() {
            addCriterion("LikeTime is not null");
            return (Criteria) this;
        }

        public Criteria andLiketimeEqualTo(Date value) {
            addCriterion("LikeTime =", value, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeNotEqualTo(Date value) {
            addCriterion("LikeTime <>", value, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeGreaterThan(Date value) {
            addCriterion("LikeTime >", value, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LikeTime >=", value, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeLessThan(Date value) {
            addCriterion("LikeTime <", value, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeLessThanOrEqualTo(Date value) {
            addCriterion("LikeTime <=", value, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeIn(List<Date> values) {
            addCriterion("LikeTime in", values, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeNotIn(List<Date> values) {
            addCriterion("LikeTime not in", values, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeBetween(Date value1, Date value2) {
            addCriterion("LikeTime between", value1, value2, "liketime");
            return (Criteria) this;
        }

        public Criteria andLiketimeNotBetween(Date value1, Date value2) {
            addCriterion("LikeTime not between", value1, value2, "liketime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table show_user
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 07 12:12:56 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table show_user
     *
     * @mbggenerated Thu Jul 07 12:12:56 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}