package com.yinlian.wssc.web.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class showarticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public showarticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andImgoneIsNull() {
            addCriterion("ImgOne is null");
            return (Criteria) this;
        }

        public Criteria andImgoneIsNotNull() {
            addCriterion("ImgOne is not null");
            return (Criteria) this;
        }

        public Criteria andImgoneEqualTo(String value) {
            addCriterion("ImgOne =", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneNotEqualTo(String value) {
            addCriterion("ImgOne <>", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneGreaterThan(String value) {
            addCriterion("ImgOne >", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneGreaterThanOrEqualTo(String value) {
            addCriterion("ImgOne >=", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneLessThan(String value) {
            addCriterion("ImgOne <", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneLessThanOrEqualTo(String value) {
            addCriterion("ImgOne <=", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneLike(String value) {
            addCriterion("ImgOne like", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneNotLike(String value) {
            addCriterion("ImgOne not like", value, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneIn(List<String> values) {
            addCriterion("ImgOne in", values, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneNotIn(List<String> values) {
            addCriterion("ImgOne not in", values, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneBetween(String value1, String value2) {
            addCriterion("ImgOne between", value1, value2, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgoneNotBetween(String value1, String value2) {
            addCriterion("ImgOne not between", value1, value2, "imgone");
            return (Criteria) this;
        }

        public Criteria andImgtwoIsNull() {
            addCriterion("ImgTwo is null");
            return (Criteria) this;
        }

        public Criteria andImgtwoIsNotNull() {
            addCriterion("ImgTwo is not null");
            return (Criteria) this;
        }

        public Criteria andImgtwoEqualTo(String value) {
            addCriterion("ImgTwo =", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoNotEqualTo(String value) {
            addCriterion("ImgTwo <>", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoGreaterThan(String value) {
            addCriterion("ImgTwo >", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoGreaterThanOrEqualTo(String value) {
            addCriterion("ImgTwo >=", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoLessThan(String value) {
            addCriterion("ImgTwo <", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoLessThanOrEqualTo(String value) {
            addCriterion("ImgTwo <=", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoLike(String value) {
            addCriterion("ImgTwo like", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoNotLike(String value) {
            addCriterion("ImgTwo not like", value, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoIn(List<String> values) {
            addCriterion("ImgTwo in", values, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoNotIn(List<String> values) {
            addCriterion("ImgTwo not in", values, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoBetween(String value1, String value2) {
            addCriterion("ImgTwo between", value1, value2, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgtwoNotBetween(String value1, String value2) {
            addCriterion("ImgTwo not between", value1, value2, "imgtwo");
            return (Criteria) this;
        }

        public Criteria andImgthrIsNull() {
            addCriterion("ImgThr is null");
            return (Criteria) this;
        }

        public Criteria andImgthrIsNotNull() {
            addCriterion("ImgThr is not null");
            return (Criteria) this;
        }

        public Criteria andImgthrEqualTo(String value) {
            addCriterion("ImgThr =", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrNotEqualTo(String value) {
            addCriterion("ImgThr <>", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrGreaterThan(String value) {
            addCriterion("ImgThr >", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrGreaterThanOrEqualTo(String value) {
            addCriterion("ImgThr >=", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrLessThan(String value) {
            addCriterion("ImgThr <", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrLessThanOrEqualTo(String value) {
            addCriterion("ImgThr <=", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrLike(String value) {
            addCriterion("ImgThr like", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrNotLike(String value) {
            addCriterion("ImgThr not like", value, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrIn(List<String> values) {
            addCriterion("ImgThr in", values, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrNotIn(List<String> values) {
            addCriterion("ImgThr not in", values, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrBetween(String value1, String value2) {
            addCriterion("ImgThr between", value1, value2, "imgthr");
            return (Criteria) this;
        }

        public Criteria andImgthrNotBetween(String value1, String value2) {
            addCriterion("ImgThr not between", value1, value2, "imgthr");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("UserID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("UserID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("UserID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("UserID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("UserID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("UserID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("UserID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("UserID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("UserID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("UserID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("UserID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("NickName is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("NickName is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("NickName =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("NickName <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("NickName >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("NickName >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("NickName <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("NickName <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("NickName like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("NickName not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("NickName in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("NickName not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("NickName between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("NickName not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andProidIsNull() {
            addCriterion("ProID is null");
            return (Criteria) this;
        }

        public Criteria andProidIsNotNull() {
            addCriterion("ProID is not null");
            return (Criteria) this;
        }

        public Criteria andProidEqualTo(Integer value) {
            addCriterion("ProID =", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotEqualTo(Integer value) {
            addCriterion("ProID <>", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidGreaterThan(Integer value) {
            addCriterion("ProID >", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ProID >=", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidLessThan(Integer value) {
            addCriterion("ProID <", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidLessThanOrEqualTo(Integer value) {
            addCriterion("ProID <=", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidIn(List<Integer> values) {
            addCriterion("ProID in", values, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotIn(List<Integer> values) {
            addCriterion("ProID not in", values, "proid");
            return (Criteria) this;
        }

        public Criteria andProidBetween(Integer value1, Integer value2) {
            addCriterion("ProID between", value1, value2, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotBetween(Integer value1, Integer value2) {
            addCriterion("ProID not between", value1, value2, "proid");
            return (Criteria) this;
        }

        public Criteria andPronameIsNull() {
            addCriterion("ProName is null");
            return (Criteria) this;
        }

        public Criteria andPronameIsNotNull() {
            addCriterion("ProName is not null");
            return (Criteria) this;
        }

        public Criteria andPronameEqualTo(String value) {
            addCriterion("ProName =", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotEqualTo(String value) {
            addCriterion("ProName <>", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThan(String value) {
            addCriterion("ProName >", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThanOrEqualTo(String value) {
            addCriterion("ProName >=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThan(String value) {
            addCriterion("ProName <", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThanOrEqualTo(String value) {
            addCriterion("ProName <=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLike(String value) {
            addCriterion("ProName like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotLike(String value) {
            addCriterion("ProName not like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameIn(List<String> values) {
            addCriterion("ProName in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotIn(List<String> values) {
            addCriterion("ProName not in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameBetween(String value1, String value2) {
            addCriterion("ProName between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotBetween(String value1, String value2) {
            addCriterion("ProName not between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPropriceIsNull() {
            addCriterion("ProPrice is null");
            return (Criteria) this;
        }

        public Criteria andPropriceIsNotNull() {
            addCriterion("ProPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPropriceEqualTo(Float value) {
            addCriterion("ProPrice =", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotEqualTo(Float value) {
            addCriterion("ProPrice <>", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceGreaterThan(Float value) {
            addCriterion("ProPrice >", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceGreaterThanOrEqualTo(Float value) {
            addCriterion("ProPrice >=", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceLessThan(Float value) {
            addCriterion("ProPrice <", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceLessThanOrEqualTo(Float value) {
            addCriterion("ProPrice <=", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceIn(List<Float> values) {
            addCriterion("ProPrice in", values, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotIn(List<Float> values) {
            addCriterion("ProPrice not in", values, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceBetween(Float value1, Float value2) {
            addCriterion("ProPrice between", value1, value2, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotBetween(Float value1, Float value2) {
            addCriterion("ProPrice not between", value1, value2, "proprice");
            return (Criteria) this;
        }

        public Criteria andProimgIsNull() {
            addCriterion("ProImg is null");
            return (Criteria) this;
        }

        public Criteria andProimgIsNotNull() {
            addCriterion("ProImg is not null");
            return (Criteria) this;
        }

        public Criteria andProimgEqualTo(String value) {
            addCriterion("ProImg =", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgNotEqualTo(String value) {
            addCriterion("ProImg <>", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgGreaterThan(String value) {
            addCriterion("ProImg >", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgGreaterThanOrEqualTo(String value) {
            addCriterion("ProImg >=", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgLessThan(String value) {
            addCriterion("ProImg <", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgLessThanOrEqualTo(String value) {
            addCriterion("ProImg <=", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgLike(String value) {
            addCriterion("ProImg like", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgNotLike(String value) {
            addCriterion("ProImg not like", value, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgIn(List<String> values) {
            addCriterion("ProImg in", values, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgNotIn(List<String> values) {
            addCriterion("ProImg not in", values, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgBetween(String value1, String value2) {
            addCriterion("ProImg between", value1, value2, "proimg");
            return (Criteria) this;
        }

        public Criteria andProimgNotBetween(String value1, String value2) {
            addCriterion("ProImg not between", value1, value2, "proimg");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table showarticle
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 07 12:08:50 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}