package com.yinlian.wssc.web.po;

public class SpecialProtype {

    private Integer id;

    private Integer specialid;

    private String name;

    private String showname;

    private String img;

    private Integer orderby;
    
    private Integer mark;

    public Integer getMark() {
		return mark;
	}

	public void setMark(Integer mark) {
		this.mark = mark;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialprotype.ID
     *
     * @param id the value for specialprotype.ID
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialprotype.SpecialID
     *
     * @return the value of specialprotype.SpecialID
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public Integer getSpecialid() {
        return specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialprotype.SpecialID
     *
     * @param specialid the value for specialprotype.SpecialID
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public void setSpecialid(Integer specialid) {
        this.specialid = specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialprotype.Name
     *
     * @return the value of specialprotype.Name
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialprotype.Name
     *
     * @param name the value for specialprotype.Name
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialprotype.ShowName
     *
     * @return the value of specialprotype.ShowName
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public String getShowname() {
        return showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialprotype.ShowName
     *
     * @param showname the value for specialprotype.ShowName
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public void setShowname(String showname) {
        this.showname = showname == null ? null : showname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialprotype.Img
     *
     * @return the value of specialprotype.Img
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialprotype.Img
     *
     * @param img the value for specialprotype.Img
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialprotype.OrderBy
     *
     * @return the value of specialprotype.OrderBy
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialprotype.OrderBy
     *
     * @param orderby the value for specialprotype.OrderBy
     *
     * @mbggenerated Thu Oct 20 16:12:41 CST 2016
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }
}