package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.search.BillsOrderCriteria;
import com.yinlian.wssc.web.dto.BillsOrderDto;
import com.yinlian.wssc.web.po.OrderBills;
import com.yinlian.wssc.web.po.OrderBillsExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderBillsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int countByExample(OrderBillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int deleteByExample(OrderBillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int insert(OrderBills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int insertSelective(OrderBills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    List<OrderBills> selectByExample(OrderBillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    OrderBills selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderBills record, @Param("example") OrderBillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int updateByExample(@Param("record") OrderBills record, @Param("example") OrderBillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int updateByPrimaryKeySelective(OrderBills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderbills
     *
     * @mbggenerated Wed Oct 18 18:18:05 CST 2017
     */
    int updateByPrimaryKey(OrderBills record);
    
    List<OrderBills> selectBills(@Param("criteria") BillsOrderCriteria criteria) throws Exception;

	int inserList(List<OrderBills> billsList)throws Exception;

	List<OrderBills> selectOrderBillsByPage(PageBeanUtil pageBeanUtil)throws Exception;

	List<BillsOrderDto> selectBillsOrderByPage(PageBeanUtil pageBeanUtil)throws Exception;
    
}