package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.web.po.showarticle;
import com.yinlian.wssc.web.po.showarticleExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface showarticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int countByExample(showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int deleteByExample(showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int insert(showarticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int insertSelective(showarticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    List<showarticle> selectByExampleWithBLOBs(showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    List<showarticle> selectByExample(showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    showarticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") showarticle record, @Param("example") showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") showarticle record, @Param("example") showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int updateByExample(@Param("record") showarticle record, @Param("example") showarticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int updateByPrimaryKeySelective(showarticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(showarticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showarticle
     *
     * @mbggenerated Thu Jul 07 12:08:50 CST 2016
     */
    int updateByPrimaryKey(showarticle record);

	List<showarticle> getshowPage(PageBeanUtil pageBeanUtil) throws Exception;

	List<showarticle> getPublicPage(PageBeanUtil pageBeanUtil) throws Exception;

	List<showarticle> getLikePage(PageBeanUtil pageBeanUtil) throws Exception;
}