package com.yinlian.wssc.web.po;

import java.util.Date;

public class VGroupShop {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.id
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.imgurl
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private String imgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.sid
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.title
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.endtime
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.starttime
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Date starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.isower
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer isower;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.num
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.pnum
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer pnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.price
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.yprice
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Double yprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.auditing
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer auditing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.state
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.ynum
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer ynum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.sname
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private String sname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.cname
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.cid
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_group_shop.depict
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	private String depict;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.id
	 * @return  the value of v_group_shop.id
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.id
	 * @param id  the value for v_group_shop.id
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.imgurl
	 * @return  the value of v_group_shop.imgurl
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public String getImgurl() {
		return imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.imgurl
	 * @param imgurl  the value for v_group_shop.imgurl
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setImgurl(String imgurl) {
		this.imgurl = imgurl == null ? null : imgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.sid
	 * @return  the value of v_group_shop.sid
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.sid
	 * @param sid  the value for v_group_shop.sid
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.title
	 * @return  the value of v_group_shop.title
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.title
	 * @param title  the value for v_group_shop.title
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.endtime
	 * @return  the value of v_group_shop.endtime
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.endtime
	 * @param endtime  the value for v_group_shop.endtime
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.starttime
	 * @return  the value of v_group_shop.starttime
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.starttime
	 * @param starttime  the value for v_group_shop.starttime
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.isower
	 * @return  the value of v_group_shop.isower
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getIsower() {
		return isower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.isower
	 * @param isower  the value for v_group_shop.isower
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setIsower(Integer isower) {
		this.isower = isower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.num
	 * @return  the value of v_group_shop.num
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.num
	 * @param num  the value for v_group_shop.num
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.pnum
	 * @return  the value of v_group_shop.pnum
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getPnum() {
		return pnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.pnum
	 * @param pnum  the value for v_group_shop.pnum
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setPnum(Integer pnum) {
		this.pnum = pnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.price
	 * @return  the value of v_group_shop.price
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.price
	 * @param price  the value for v_group_shop.price
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.yprice
	 * @return  the value of v_group_shop.yprice
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Double getYprice() {
		return yprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.yprice
	 * @param yprice  the value for v_group_shop.yprice
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setYprice(Double yprice) {
		this.yprice = yprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.auditing
	 * @return  the value of v_group_shop.auditing
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getAuditing() {
		return auditing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.auditing
	 * @param auditing  the value for v_group_shop.auditing
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setAuditing(Integer auditing) {
		this.auditing = auditing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.state
	 * @return  the value of v_group_shop.state
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.state
	 * @param state  the value for v_group_shop.state
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.ynum
	 * @return  the value of v_group_shop.ynum
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getYnum() {
		return ynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.ynum
	 * @param ynum  the value for v_group_shop.ynum
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setYnum(Integer ynum) {
		this.ynum = ynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.sname
	 * @return  the value of v_group_shop.sname
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.sname
	 * @param sname  the value for v_group_shop.sname
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setSname(String sname) {
		this.sname = sname == null ? null : sname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.cname
	 * @return  the value of v_group_shop.cname
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.cname
	 * @param cname  the value for v_group_shop.cname
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setCname(String cname) {
		this.cname = cname == null ? null : cname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.cid
	 * @return  the value of v_group_shop.cid
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.cid
	 * @param cid  the value for v_group_shop.cid
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_group_shop.depict
	 * @return  the value of v_group_shop.depict
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public String getDepict() {
		return depict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_group_shop.depict
	 * @param depict  the value for v_group_shop.depict
	 * @mbggenerated  Thu Sep 08 15:33:50 CST 2016
	 */
	public void setDepict(String depict) {
		this.depict = depict == null ? null : depict.trim();
	}
}