package com.yinlian.wssc.web.po;

import java.util.Date;

public class SnewsRImgs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.id
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.url
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.title
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.snewsid
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private Integer snewsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.sort
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.createtime
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.img
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.ex1
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String ex1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.ex2
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String ex2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.ex3
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String ex3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.ex4
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String ex4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_news_r_imgs.ex5
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    private String ex5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.id
     *
     * @return the value of s_news_r_imgs.id
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.id
     *
     * @param id the value for s_news_r_imgs.id
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.url
     *
     * @return the value of s_news_r_imgs.url
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.url
     *
     * @param url the value for s_news_r_imgs.url
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.title
     *
     * @return the value of s_news_r_imgs.title
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.title
     *
     * @param title the value for s_news_r_imgs.title
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.snewsid
     *
     * @return the value of s_news_r_imgs.snewsid
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public Integer getSnewsid() {
        return snewsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.snewsid
     *
     * @param snewsid the value for s_news_r_imgs.snewsid
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setSnewsid(Integer snewsid) {
        this.snewsid = snewsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.sort
     *
     * @return the value of s_news_r_imgs.sort
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.sort
     *
     * @param sort the value for s_news_r_imgs.sort
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.createtime
     *
     * @return the value of s_news_r_imgs.createtime
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.createtime
     *
     * @param createtime the value for s_news_r_imgs.createtime
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.img
     *
     * @return the value of s_news_r_imgs.img
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.img
     *
     * @param img the value for s_news_r_imgs.img
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.ex1
     *
     * @return the value of s_news_r_imgs.ex1
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getEx1() {
        return ex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.ex1
     *
     * @param ex1 the value for s_news_r_imgs.ex1
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setEx1(String ex1) {
        this.ex1 = ex1 == null ? null : ex1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.ex2
     *
     * @return the value of s_news_r_imgs.ex2
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getEx2() {
        return ex2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.ex2
     *
     * @param ex2 the value for s_news_r_imgs.ex2
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setEx2(String ex2) {
        this.ex2 = ex2 == null ? null : ex2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.ex3
     *
     * @return the value of s_news_r_imgs.ex3
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getEx3() {
        return ex3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.ex3
     *
     * @param ex3 the value for s_news_r_imgs.ex3
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setEx3(String ex3) {
        this.ex3 = ex3 == null ? null : ex3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.ex4
     *
     * @return the value of s_news_r_imgs.ex4
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getEx4() {
        return ex4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.ex4
     *
     * @param ex4 the value for s_news_r_imgs.ex4
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setEx4(String ex4) {
        this.ex4 = ex4 == null ? null : ex4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_news_r_imgs.ex5
     *
     * @return the value of s_news_r_imgs.ex5
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public String getEx5() {
        return ex5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_news_r_imgs.ex5
     *
     * @param ex5 the value for s_news_r_imgs.ex5
     *
     * @mbggenerated Wed Sep 14 13:32:17 CST 2016
     */
    public void setEx5(String ex5) {
        this.ex5 = ex5 == null ? null : ex5.trim();
    }
}