package com.yinlian.wssc.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yinlian.wssc.web.po.Groupbuyinfo;
import com.yinlian.wssc.web.po.GroupbuyinfoExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

public interface GroupbuyinfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int countByExample(GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int deleteByExample(GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int insert(Groupbuyinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int insertSelective(Groupbuyinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	List<Groupbuyinfo> selectByExampleWithBLOBs(GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	List<Groupbuyinfo> selectByExample(GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	Groupbuyinfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Groupbuyinfo record, @Param("example") GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") Groupbuyinfo record, @Param("example") GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int updateByExample(@Param("record") Groupbuyinfo record, @Param("example") GroupbuyinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int updateByPrimaryKeySelective(Groupbuyinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Groupbuyinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groupbuyinfo
	 * @mbggenerated  Mon Sep 12 11:27:53 CST 2016
	 */
	int updateByPrimaryKey(Groupbuyinfo record);

	List<Groupbuyinfo> getListPage(PageBeanUtil pageBeanUtil) throws Exception;

	Integer changestate(@Param("id") Integer id, @Param("state") Integer state) throws Exception;

	int updateAudit(Integer id, Integer auditing) throws Exception;
}