package com.yinlian.wssc.web.mapper;

import com.yinlian.wssc.web.dto.FindRelateArticlesDto;
import com.yinlian.wssc.web.dto.FindRelateShopDto;
import com.yinlian.wssc.web.dto.FindRelateTopicDto;
import com.yinlian.wssc.web.po.FindRelation;
import com.yinlian.wssc.web.po.FindRelationExample;
import com.yinlian.wssc.web.util.PageBeanUtil;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FindRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int countByExample(FindRelationExample example) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int deleteByExample(FindRelationExample example) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int deleteByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int insert(FindRelation record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int insertSelective(FindRelation record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    List<FindRelation> selectByExample(FindRelationExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    FindRelation selectByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") FindRelation record, @Param("example") FindRelationExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int updateByExample(@Param("record") FindRelation record, @Param("example") FindRelationExample example)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int updateByPrimaryKeySelective(FindRelation record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_relation
     *
     * @mbggenerated Sun Sep 18 10:37:46 CST 2016
     */
    int updateByPrimaryKey(FindRelation record)throws Exception;

	List<FindRelateShopDto> selectFindShopByPage(PageBeanUtil pageBeanUtil) throws Exception;

	List<FindRelateTopicDto> selectFindTopicByPage(PageBeanUtil pageBeanUtil)  throws Exception;

	List<FindRelateArticlesDto> selectFindArtByPage(PageBeanUtil pageBeanUtil)  throws Exception;

}